### PR TITLE
Hospital sean backup

### PR DESCRIPTION
**Pull request by AvidMaker12**

### CODE REVIEW

**Review by Xuanwen1101 — CHANGES_REQUESTED** [review]
You deleted the logo image and missed the update in HospitalProject-Group3/HospitalProject-Group3.csproj

**Comment by AvidMaker12** [comment]
Implemented following:

**Comment by AvidMaker12** [comment]
include logo image

departmentdatacontroller: r not needed in second part (reference id)

same issue with prescription

**Review by Xuanwen1101 — CHANGES_REQUESTED** [review]
image
Do not change the application name to your local copy name.

**Review by Xuanwen1101 — APPROVED** [review]

**Pull request merged**
